version: "3.9"
services:
  web:
    container_name: universal_auto_web
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    build: .
    env_file:
      .env
    ports:
      - "8000:8000"
      - "80:80"
    command: honcho start
    volumes:
      - .:/app

  redis:
    container_name: universal_auto_redis
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  postgres:
    container_name: universal_auto_postgres
    image: postgres:13.8
    environment:
      POSTGRES_DB: "universal_auto_dev"
      POSTGRES_USER: "universal_auto_dev"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5424:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U universal_auto_dev -d universal_auto_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  chrome:
    container_name: universal_auto_chrome
    image: selenium/standalone-chrome:latest
    hostname: chrome
    privileged: true
    shm_size: 2g
    ports:
      - "4444:4444"
    restart: always
    environment:
      SE_NODE_SESSION_TIMEOUT: 600
      SE_NODE_MAX_SESSIONS: 3
      SE_NODE_MAX_INSTANCES: 3
