# fly.toml file generated for snowy-wood-371 on 2023-02-19T22:39:32+02:00



app = "snowy-wood-371"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  strategy = "bluegreen"
  release_command = "python3 manage.py migrate --noinput"
[env]
  DEBUG = 0
  ECHO_PORT = "44300"
  PORT = "80"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = []
  entrypoint = []
  exec = []

[processes]
  web    =  "bash ./entrypoint.sh"
  worker = "celery -A auto worker --loglevel=info --without-gossip --pool=solo"
  gps    = "python3 manage.py runscript async_gps_server"
  beat   = "celery -A auto beat -l INFO"
  bot    = "python3 manage.py runscript bot"

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "requests"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  http_checks = []
  internal_port = 44300
  processes = ['gps']
  protocol = "udp"
  script_checks = []
  tcp_checks = []
  [services.concurrency]
    hard_limit = 10
    soft_limit = 5
    type = "connections"

  [[services.ports]]
    handlers = []
    port = 44300

[[services]]
  http_checks = []
  internal_port = 44300
  processes = ['gps']
  protocol = "tcp"
  script_checks = []
  tcp_checks = []
  [services.concurrency]
    hard_limit = 10
    soft_limit = 5
    type = "connections"

  [[services.ports]]
    handlers = []
    port = 44300

[[statics]]
  cache_key = "_static___app_public"
  guest_path = "/app/static"
  processes = []
  url_prefix = "/static/"
