app = "workers"
kill_signal = "SIGINT"
primary_region = "otp"
kill_timeout = 5
[env]
  DEBUG = ''
[experimental]
  auto_rollback = true
[processes]
  worker = "celery -A auto worker --loglevel=INFO -Q beat_tasks"
  gps_worker = "celery -A auto worker --loglevel=INFO  -Q gps_tasks"
  beat = "celery -A auto beat -l INFO"