app = "workers"
kill_signal = "SIGINT"
primary_region = "otp"
kill_timeout = 5
[env]
  DEBUG = 0
[experimental]
   auto_rollback = true
[processes]
  worker = "celery -A auto worker --loglevel=warning --without-gossip --pool=solo"
  beat   = "celery -A auto beat -l WARNING"
[[services]]
  auto_stop_machines = true
  auto_start_machines = true
  processes = ['worker']
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 10
    soft_limit = 5
    type = "connections"
 

