# Generated by Django 4.1 on 2023-10-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_taskscheduler_carefficiency_report_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskscheduler',
            name='interval',
            field=models.IntegerField(blank=True, verbose_name='Інтервал запуску'),
        ),
    ]
