# Generated by Django 4.1 on 2023-12-07 08:19

import django.core.validators
from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_customreport_fleetsdriversvehiclesrate_taskscheduler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_from', models.DateField(verbose_name='Дохід з')),
                ('report_to', models.DateField(verbose_name='Дохід по')),
                ('earning', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума доходу')),
            ],
            options={
                'verbose_name': 'Дохід',
                'verbose_name_plural': 'Доходи',
            },
        ),
        migrations.CreateModel(
            name='VehicleRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_from', models.DateTimeField(verbose_name='Звіт з')),
                ('report_to', models.DateTimeField(verbose_name='Звіт по')),
                ('rent_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Орендована дистанція')),
            ],
        ),
        migrations.RenameModel(
            old_name="TransactionsConversation",
            new_name="InvestorPayments"
        ),
        migrations.RemoveField(
            model_name='driver',
            name='worked',
        ),
        migrations.AddField(
            model_name='fleetorder',
            name='road_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Час в дорозі'),
        ),
        migrations.AddField(
            model_name='fleetorder',
            name='tips',
            field=models.IntegerField(null=True, verbose_name='Чайові'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)], verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^(\\+380|380|80|0)+\\d{9}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)], verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gps_imei',
            field=models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.MaxLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='licence_plate',
            field=models.CharField(max_length=24, unique=True, validators=[django.core.validators.MaxLengthValidator(24)], verbose_name='Номерний знак'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin_code',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.MaxLengthValidator(17)]),
        ),
        migrations.AddField(
            model_name='vehiclerent',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.driver', verbose_name='Водій'),
        ),
        migrations.AddField(
            model_name='vehiclerent',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнери'),
        ),
        migrations.AddField(
            model_name='vehiclerent',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vehicle', verbose_name='Автомобіль'),
        ),
        migrations.AddField(
            model_name='partnerearnings',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driver', verbose_name='Водій'),
        ),
        migrations.AddField(
            model_name='partnerearnings',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='partnerearnings',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehicle', verbose_name='Автомобіль'),
        ),
        migrations.CreateModel(
            name='FiredDriver',
            fields=[
            ],
            options={
                'verbose_name': 'Звільненого водія',
                'verbose_name_plural': 'Звільнені водії',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.driver',),
        ),
        migrations.AddField(
            model_name='investorpayments',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='investorpayments',
            name='report_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Виплата за'),
            preserve_default=False,
        ),
    ]
