# Generated by Django 4.1 on 2023-12-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_remove_driverpayments_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpayments',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонуси'),
        ),
        migrations.AddField(
            model_name='driverpayments',
            name='fines',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Штрафи'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='status',
            field=models.CharField(choices=[('CHECKING', 'Перевіряється'), ('PENDING', 'Очікується'), ('COMPLETED', 'Виплачений'), ('FAILED', 'Не сплачений')], default='CHECKING', max_length=20),
        ),
    ]
