# Generated by Django 4.1 on 2024-01-31 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_driverefficiencypolymorphic_total_orders_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehicle', verbose_name='Автомобіль'),
        ),
    ]
