# Generated by Django 4.1 on 2024-03-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carefficiency',
            name='all_brand_trips',
            field=models.IntegerField(default=0, verbose_name='Всього поїздок бренду'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='branding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.fleet', verbose_name='Бренд'),
        ),
    ]
