# Generated by Django 4.1 on 2024-04-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_carefficiency_investor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverefficiency',
            name='total_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Готівкою'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='status',
            field=models.CharField(choices=[('incorrect', 'Потребує поправок'), ('checking', 'Перевіряється'), ('pending', 'Очікується'), ('completed', 'Виплачений'), ('failed', 'Не сплачений')], default='checking', max_length=20),
        ),
    ]
